version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elevador_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Kestrel__Endpoints__Http__Url: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST:-130.250.189.175};Port=${DB_PORT:-5432};Database=${DB_NAME:-TELA_ELEVADOR};Username=${DB_USER:-dba};Password=${DB_PASSWORD:-Bb3491818835!}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: elevador_worker
    environment:
      DOTNET_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST:-130.250.189.175};Port=${DB_PORT:-5432};Database=${DB_NAME:-TELA_ELEVADOR};Username=${DB_USER:-dba};Password=${DB_PASSWORD:-Bb3491818835!}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  media_data:
