// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TELA_ELEVADOR_SERVER.EntityFrameworkCore.Persistence;

#nullable disable

namespace TELA_ELEVADOR_SERVER.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214144442_UpdateSindicoRole")]
    partial class UpdateSindicoRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InicioEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PredioId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredioId");

                    b.ToTable("Aviso", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("FonteNoticia", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Predio", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.PreferenciaNoticia", b =>
                {
                    b.Property<int>("PredioId")
                        .HasColumnType("integer");

                    b.Property<int>("FonteNoticiaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.HasKey("PredioId", "FonteNoticiaId");

                    b.HasIndex("FonteNoticiaId");

                    b.ToTable("PreferenciaNoticia", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Sindico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PredioId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredioId", "Usuario")
                        .IsUnique();

                    b.ToTable("Sindico", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Aviso", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("Avisos")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.PreferenciaNoticia", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", "FonteNoticia")
                        .WithMany("PreferenciasNoticia")
                        .HasForeignKey("FonteNoticiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("PreferenciasNoticia")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteNoticia");

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Sindico", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("Sindicos")
                        .HasForeignKey("PredioId");

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", b =>
                {
                    b.Navigation("PreferenciasNoticia");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("PreferenciasNoticia");

                    b.Navigation("Sindicos");
                });
#pragma warning restore 612, 618
        }
    }
}
