// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TELA_ELEVADOR_SERVER.EntityFrameworkCore.Persistence;

#nullable disable

namespace TELA_ELEVADOR_SERVER.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221195211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InicioEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PredioId")
                        .HasColumnType("integer");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("normal");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredioId");

                    b.ToTable("Aviso", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Cidade_Nome_Unique");

                    b.ToTable("Cidade", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.ClimaPrevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoWmo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TemperaturaMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("TemperaturaMinima")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId", "Data")
                        .IsUnique()
                        .HasDatabaseName("IX_ClimaPrevisao_CidadeId_Data_Unique");

                    b.ToTable("ClimaPrevisao", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("FonteNoticia", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FonteChave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FonteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PubDateRaw")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PublicadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("FonteChave");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("PublicadoEmUtc");

                    b.ToTable("Noticia", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CidadeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrientationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("auto");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Predio", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.PreferenciaNoticia", b =>
                {
                    b.Property<int>("PredioId")
                        .HasColumnType("integer");

                    b.Property<int>("FonteNoticiaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.HasKey("PredioId", "FonteNoticiaId");

                    b.HasIndex("FonteNoticiaId");

                    b.ToTable("PreferenciaNoticia", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Sindico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PredioId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredioId", "Usuario")
                        .IsUnique();

                    b.ToTable("Sindico", (string)null);
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Aviso", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("Avisos")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.ClimaPrevisao", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Cidade", "Cidade")
                        .WithMany("ClimaPrevisoesData")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Predios")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.PreferenciaNoticia", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", "FonteNoticia")
                        .WithMany("PreferenciasNoticia")
                        .HasForeignKey("FonteNoticiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("PreferenciasNoticia")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteNoticia");

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Sindico", b =>
                {
                    b.HasOne("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", "Predio")
                        .WithMany("Sindicos")
                        .HasForeignKey("PredioId");

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("ClimaPrevisoesData");

                    b.Navigation("Predios");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.FonteNoticia", b =>
                {
                    b.Navigation("PreferenciasNoticia");
                });

            modelBuilder.Entity("TELA_ELEVADOR_SERVER.Domain.Entities.Predio", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("PreferenciasNoticia");

                    b.Navigation("Sindicos");
                });
#pragma warning restore 612, 618
        }
    }
}
